/**
 * Mock data for OwnGCC Talent Center (frontend-only demo).
 * Tech + Non-Tech roles with strict skill mapping.
 */

const TECH_ROLES_MAP: Record<string, string[]> = {
  "Software Developer": [
    "Data Structures",
    "Algorithms",
    "Object-Oriented Programming",
    "Git & Version Control",
    "Debugging",
    "System Design",
  ],
  "Frontend Developer": [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "TypeScript",
    "Responsive Design",
    "API Integration",
  ],
  "Backend Developer": [
    "Node.js",
    "Express",
    "REST APIs",
    "PostgreSQL",
    "Authentication",
    "Database Design",
    "Microservices",
  ],
  "Full Stack Developer": [
    "JavaScript",
    "React",
    "Node.js",
    "APIs",
    "Databases",
    "Git",
    "Deployment Basics",
  ],
  "Mobile App Developer": [
    "React Native",
    "Flutter",
    "Android / iOS Basics",
    "API Integration",
    "App Performance Optimization",
  ],
  "QA / Test Engineer": [
    "Manual Testing",
    "Test Case Design",
    "Automation Basics",
    "Selenium / Playwright",
    "Bug Tracking",
    "Quality Assurance Processes",
  ],
  "DevOps Engineer": [
    "Docker",
    "Kubernetes",
    "CI/CD Pipelines",
    "Cloud Platforms (AWS/Azure)",
    "Linux",
    "Monitoring & Logging",
  ],
  "AI / ML Engineer": [
    "Python",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow / PyTorch",
    "Data Modeling",
    "Model Evaluation",
  ],
};

const NON_TECH_ROLES_MAP: Record<string, string[]> = {
  "Product Manager": [
    "Requirement Gathering",
    "Product Roadmapping",
    "Stakeholder Communication",
    "Agile Methodologies",
    "Market Research",
    "Prioritization",
  ],
  "Project Manager": [
    "Project Planning",
    "Risk Management",
    "Team Coordination",
    "Agile / Scrum",
    "Client Communication",
    "Delivery Management",
  ],
  "Business Analyst": [
    "Business Requirement Analysis",
    "Process Mapping",
    "Documentation",
    "Stakeholder Interviews",
    "Data Analysis",
  ],
  "UI / UX Designer": [
    "User Research",
    "Wireframing",
    "Prototyping",
    "Figma",
    "Design Systems",
    "Usability Testing",
  ],
  "Graphic Designer": [
    "Adobe Photoshop",
    "Illustrator",
    "Branding",
    "Visual Design",
    "Creative Thinking",
  ],
  "Digital Marketing Executive": [
    "Social Media Marketing",
    "Campaign Planning",
    "Content Strategy",
    "Analytics",
    "Performance Tracking",
  ],
  "SEO Specialist": [
    "Keyword Research",
    "On-page SEO",
    "Technical SEO",
    "Link Building",
    "SEO Tools (Ahrefs, SEMrush)",
  ],
  "Content Writer": [
    "Content Creation",
    "Copywriting",
    "Research",
    "SEO Writing",
    "Editing & Proofreading",
  ],
  "Technical Recruiter": [
    "Talent Sourcing",
    "Candidate Screening",
    "Interview Coordination",
    "ATS Tools",
    "Hiring Processes",
  ],
  "HR Executive": [
    "Employee Relations",
    "HR Operations",
    "Onboarding",
    "Policy Management",
    "Payroll Coordination",
  ],
  "Sales Executive": [
    "Lead Generation",
    "Client Communication",
    "CRM Tools",
    "Negotiation",
    "Closing Deals",
  ],
  "Business Development Manager": [
    "Market Expansion",
    "Strategic Partnerships",
    "Revenue Growth",
    "Proposal Writing",
    "Client Acquisition",
  ],
  "Customer Support Executive": [
    "Customer Communication",
    "Issue Resolution",
    "CRM Systems",
    "Ticket Management",
    "Service Quality",
  ],
  "Operations Manager": [
    "Process Optimization",
    "Team Management",
    "Workflow Planning",
    "Performance Tracking",
  ],
  "Finance Executive": [
    "Financial Reporting",
    "Budgeting",
    "Accounting Basics",
    "Compliance",
    "Data Accuracy",
  ],
};

export const ROLE_SKILL_MAP: Record<string, string[]> = {
  ...TECH_ROLES_MAP,
  ...NON_TECH_ROLES_MAP,
};

export const TECH_ROLES = Object.keys(TECH_ROLES_MAP);
export const NON_TECH_ROLES = Object.keys(NON_TECH_ROLES_MAP);
export const ROLE_OPTIONS = Object.keys(ROLE_SKILL_MAP);

export type DummyCandidate = {
  id: number;
  name: string;
  role: string;
  experience: number;
  skills: string[];
  availability: string;
  monthlyCost: number;
  project: string;
  readyToRelocate: boolean;
};

/** One candidate per role for demo; dashboard filters by selected role. */
export const DUMMY_CANDIDATES: DummyCandidate[] = [
  {
    id: 1,
    name: "Rahul Mehta",
    role: "Frontend Developer",
    experience: 5,
    skills: ["React", "TypeScript", "HTML", "CSS", "API Integration"],
    availability: "Immediate",
    monthlyCost: 220000,
    project: "Built a dashboard for a fintech platform used by 20k+ users.",
    readyToRelocate: true,
  },
  {
    id: 2,
    name: "Sneha Kapoor",
    role: "Backend Developer",
    experience: 6,
    skills: ["Node.js", "PostgreSQL", "Microservices", "REST APIs"],
    availability: "15 days",
    monthlyCost: 260000,
    project: "Designed backend architecture for a logistics SaaS platform.",
    readyToRelocate: false,
  },
  {
    id: 3,
    name: "Arjun Rao",
    role: "AI / ML Engineer",
    experience: 4,
    skills: ["Python", "Machine Learning", "TensorFlow / PyTorch"],
    availability: "30 days",
    monthlyCost: 240000,
    project: "Developed resume screening AI for HR automation.",
    readyToRelocate: true,
  },
  {
    id: 4,
    name: "Priya Sharma",
    role: "Software Developer",
    experience: 4,
    skills: ["Data Structures", "Algorithms", "System Design", "Git"],
    availability: "Immediate",
    monthlyCost: 200000,
    project: "Core services for a payments gateway handling 50k TPS.",
    readyToRelocate: true,
  },
  {
    id: 5,
    name: "Vikram Singh",
    role: "Full Stack Developer",
    experience: 5,
    skills: ["React", "Node.js", "APIs", "Databases", "Deployment Basics"],
    availability: "15 days",
    monthlyCost: 230000,
    project: "End-to-end e-commerce platform for a retail brand.",
    readyToRelocate: false,
  },
  {
    id: 6,
    name: "Kavita Reddy",
    role: "Mobile App Developer",
    experience: 4,
    skills: ["React Native", "Flutter", "API Integration"],
    availability: "Immediate",
    monthlyCost: 210000,
    project: "Consumer app with 100k+ downloads.",
    readyToRelocate: true,
  },
  {
    id: 7,
    name: "Anil Kumar",
    role: "QA / Test Engineer",
    experience: 4,
    skills: ["Manual Testing", "Selenium / Playwright", "Bug Tracking"],
    availability: "30 days",
    monthlyCost: 180000,
    project: "Test automation for a healthcare SaaS product.",
    readyToRelocate: false,
  },
  {
    id: 8,
    name: "Deepa Nair",
    role: "DevOps Engineer",
    experience: 5,
    skills: ["Docker", "Kubernetes", "CI/CD Pipelines", "AWS"],
    availability: "Immediate",
    monthlyCost: 250000,
    project: "Infrastructure and deployment pipelines for multi-tenant SaaS.",
    readyToRelocate: true,
  },
  {
    id: 9,
    name: "Rajesh Iyer",
    role: "Product Manager",
    experience: 6,
    skills: ["Product Roadmapping", "Agile Methodologies", "Stakeholder Communication"],
    availability: "15 days",
    monthlyCost: 280000,
    project: "Led product strategy for a B2B analytics platform.",
    readyToRelocate: false,
  },
  {
    id: 10,
    name: "Meera Krishnan",
    role: "Project Manager",
    experience: 5,
    skills: ["Agile / Scrum", "Client Communication", "Delivery Management"],
    availability: "Immediate",
    monthlyCost: 240000,
    project: "Delivered 12+ projects for global clients on time.",
    readyToRelocate: true,
  },
  {
    id: 11,
    name: "Suresh Patel",
    role: "Business Analyst",
    experience: 4,
    skills: ["Process Mapping", "Documentation", "Data Analysis"],
    availability: "15 days",
    monthlyCost: 190000,
    project: "Requirements and process design for banking workflows.",
    readyToRelocate: false,
  },
  {
    id: 12,
    name: "Divya Menon",
    role: "UI / UX Designer",
    experience: 4,
    skills: ["Figma", "Prototyping", "User Research", "Design Systems"],
    availability: "Immediate",
    monthlyCost: 200000,
    project: "Design system and UX for a fintech app.",
    readyToRelocate: true,
  },
  {
    id: 13,
    name: "Amit Desai",
    role: "Digital Marketing Executive",
    experience: 3,
    skills: ["Social Media Marketing", "Content Strategy", "Analytics"],
    availability: "Immediate",
    monthlyCost: 150000,
    project: "Grew organic traffic by 200% for an ed-tech brand.",
    readyToRelocate: true,
  },
  {
    id: 14,
    name: "Pooja Gupta",
    role: "HR Executive",
    experience: 4,
    skills: ["Onboarding", "HR Operations", "Policy Management"],
    availability: "15 days",
    monthlyCost: 170000,
    project: "Scaled HR operations for a 500+ employee startup.",
    readyToRelocate: false,
  },
  {
    id: 15,
    name: "Karan Malhotra",
    role: "Sales Executive",
    experience: 4,
    skills: ["Lead Generation", "CRM Tools", "Closing Deals"],
    availability: "Immediate",
    monthlyCost: 185000,
    project: "Exceeded targets by 140% in B2B software sales.",
    readyToRelocate: true,
  },
  // Extra Frontend Developers
  {
    id: 16,
    name: "Neha Verma",
    role: "Frontend Developer",
    experience: 3,
    skills: ["React", "JavaScript", "HTML", "CSS", "Responsive Design"],
    availability: "Immediate",
    monthlyCost: 180000,
    project: "Redesigned customer portal for an insurance company.",
    readyToRelocate: false,
  },
  {
    id: 17,
    name: "Aditya Joshi",
    role: "Frontend Developer",
    experience: 6,
    skills: ["React", "TypeScript", "API Integration", "Responsive Design"],
    availability: "15 days",
    monthlyCost: 250000,
    project: "Led frontend for a real estate listing platform.",
    readyToRelocate: true,
  },
  // Extra Backend Developers
  {
    id: 18,
    name: "Ritu Agarwal",
    role: "Backend Developer",
    experience: 4,
    skills: ["Node.js", "Express", "REST APIs", "PostgreSQL"],
    availability: "30 days",
    monthlyCost: 220000,
    project: "API services for a food delivery aggregator.",
    readyToRelocate: true,
  },
  {
    id: 19,
    name: "Varun Bhat",
    role: "Backend Developer",
    experience: 7,
    skills: ["Microservices", "Database Design", "Authentication", "Node.js"],
    availability: "15 days",
    monthlyCost: 300000,
    project: "Scalable backend for a gaming platform.",
    readyToRelocate: false,
  },
  // Extra Full Stack
  {
    id: 20,
    name: "Anjali Krishnan",
    role: "Full Stack Developer",
    experience: 4,
    skills: ["JavaScript", "React", "Node.js", "Git", "APIs"],
    availability: "Immediate",
    monthlyCost: 210000,
    project: "Internal tools and dashboards for a logistics firm.",
    readyToRelocate: true,
  },
  // Extra Software Developer
  {
    id: 21,
    name: "Rohan Saxena",
    role: "Software Developer",
    experience: 5,
    skills: ["Algorithms", "System Design", "OOP", "Git & Version Control"],
    availability: "15 days",
    monthlyCost: 230000,
    project: "Low-latency trading system components.",
    readyToRelocate: false,
  },
  // Extra AI/ML
  {
    id: 22,
    name: "Lakshmi Pillai",
    role: "AI / ML Engineer",
    experience: 5,
    skills: ["Python", "Deep Learning", "Data Modeling", "Model Evaluation"],
    availability: "30 days",
    monthlyCost: 270000,
    project: "NLP models for customer support automation.",
    readyToRelocate: true,
  },
  // Extra Mobile, QA, DevOps
  {
    id: 23,
    name: "Sanjay Menon",
    role: "Mobile App Developer",
    experience: 3,
    skills: ["Flutter", "API Integration", "Android / iOS Basics"],
    availability: "Immediate",
    monthlyCost: 190000,
    project: "Fitness and wellness app with 50k+ users.",
    readyToRelocate: true,
  },
  {
    id: 24,
    name: "Pooja Nambiar",
    role: "QA / Test Engineer",
    experience: 5,
    skills: ["Test Case Design", "Automation Basics", "Selenium / Playwright", "Bug Tracking"],
    availability: "15 days",
    monthlyCost: 195000,
    project: "E2E test suite for a banking application.",
    readyToRelocate: false,
  },
  {
    id: 25,
    name: "Karthik Reddy",
    role: "DevOps Engineer",
    experience: 4,
    skills: ["Docker", "CI/CD Pipelines", "Linux", "Monitoring & Logging"],
    availability: "30 days",
    monthlyCost: 235000,
    project: "Cloud migration for a media streaming service.",
    readyToRelocate: true,
  },
  // Product & Project
  {
    id: 26,
    name: "Shweta Iyer",
    role: "Product Manager",
    experience: 4,
    skills: ["Requirement Gathering", "Market Research", "Prioritization", "Agile Methodologies"],
    availability: "Immediate",
    monthlyCost: 260000,
    project: "Launched a B2C subscription product from 0 to 10k users.",
    readyToRelocate: false,
  },
  {
    id: 27,
    name: "Vikram Pillai",
    role: "Project Manager",
    experience: 6,
    skills: ["Project Planning", "Risk Management", "Agile / Scrum", "Client Communication"],
    availability: "15 days",
    monthlyCost: 265000,
    project: "Managed 8-member team for enterprise CRM rollout.",
    readyToRelocate: true,
  },
  // Business Analyst, UI/UX, Graphic
  {
    id: 28,
    name: "Preeti Rao",
    role: "Business Analyst",
    experience: 5,
    skills: ["Business Requirement Analysis", "Stakeholder Interviews", "Data Analysis", "Process Mapping"],
    availability: "Immediate",
    monthlyCost: 200000,
    project: "Requirements for core banking transformation.",
    readyToRelocate: true,
  },
  {
    id: 29,
    name: "Rahul Nair",
    role: "UI / UX Designer",
    experience: 3,
    skills: ["Figma", "Wireframing", "Prototyping", "Usability Testing"],
    availability: "15 days",
    monthlyCost: 175000,
    project: "UX overhaul for a healthcare booking app.",
    readyToRelocate: false,
  },
  {
    id: 30,
    name: "Maya Krishnan",
    role: "Graphic Designer",
    experience: 4,
    skills: ["Adobe Photoshop", "Illustrator", "Branding", "Visual Design"],
    availability: "Immediate",
    monthlyCost: 165000,
    project: "Brand identity and marketing collaterals for 5+ startups.",
    readyToRelocate: true,
  },
  // Digital Marketing, SEO, Content
  {
    id: 31,
    name: "Ravi Singh",
    role: "Digital Marketing Executive",
    experience: 4,
    skills: ["Campaign Planning", "Performance Tracking", "Social Media Marketing", "Analytics"],
    availability: "30 days",
    monthlyCost: 160000,
    project: "Managed paid campaigns with 3x ROAS.",
    readyToRelocate: false,
  },
  {
    id: 32,
    name: "Sonali Desai",
    role: "SEO Specialist",
    experience: 3,
    skills: ["Keyword Research", "On-page SEO", "Technical SEO", "SEO Tools (Ahrefs, SEMrush)"],
    availability: "Immediate",
    monthlyCost: 155000,
    project: "Improved organic traffic by 150% for an e-commerce client.",
    readyToRelocate: true,
  },
  {
    id: 33,
    name: "Arun Menon",
    role: "Content Writer",
    experience: 4,
    skills: ["Content Creation", "Copywriting", "SEO Writing", "Editing & Proofreading"],
    availability: "15 days",
    monthlyCost: 140000,
    project: "Blog and product copy for a SaaS brand.",
    readyToRelocate: false,
  },
  // Recruiter, HR, Sales, BDM, Support, Ops, Finance
  {
    id: 34,
    name: "Divya Kulkarni",
    role: "Technical Recruiter",
    experience: 5,
    skills: ["Talent Sourcing", "Candidate Screening", "Interview Coordination", "ATS Tools"],
    availability: "Immediate",
    monthlyCost: 170000,
    project: "Hired 80+ tech roles for a product company in 18 months.",
    readyToRelocate: true,
  },
  {
    id: 35,
    name: "Nitin Shah",
    role: "HR Executive",
    experience: 5,
    skills: ["Employee Relations", "Onboarding", "Policy Management", "Payroll Coordination"],
    availability: "15 days",
    monthlyCost: 180000,
    project: "Set up HR operations for a 200-person GCC.",
    readyToRelocate: false,
  },
  {
    id: 36,
    name: "Priti Mehta",
    role: "Sales Executive",
    experience: 3,
    skills: ["Lead Generation", "Client Communication", "Negotiation", "Closing Deals"],
    availability: "Immediate",
    monthlyCost: 165000,
    project: "New business sales for cloud services.",
    readyToRelocate: true,
  },
  {
    id: 37,
    name: "Rajat Verma",
    role: "Business Development Manager",
    experience: 6,
    skills: ["Market Expansion", "Strategic Partnerships", "Revenue Growth", "Client Acquisition"],
    availability: "30 days",
    monthlyCost: 290000,
    project: "Grew regional revenue by 40% through channel partnerships.",
    readyToRelocate: false,
  },
  {
    id: 38,
    name: "Kavya Srinivas",
    role: "Customer Support Executive",
    experience: 3,
    skills: ["Customer Communication", "Issue Resolution", "CRM Systems", "Ticket Management"],
    availability: "Immediate",
    monthlyCost: 135000,
    project: "Led support for a B2B SaaS product; 95% CSAT.",
    readyToRelocate: true,
  },
  {
    id: 39,
    name: "Sandeep Kumar",
    role: "Operations Manager",
    experience: 5,
    skills: ["Process Optimization", "Team Management", "Workflow Planning", "Performance Tracking"],
    availability: "15 days",
    monthlyCost: 240000,
    project: "Streamlined fulfillment operations; 30% cost reduction.",
    readyToRelocate: false,
  },
  {
    id: 40,
    name: "Anita Rao",
    role: "Finance Executive",
    experience: 4,
    skills: ["Financial Reporting", "Budgeting", "Accounting Basics", "Compliance"],
    availability: "Immediate",
    monthlyCost: 185000,
    project: "Month-end close and reporting for a mid-size GCC.",
    readyToRelocate: true,
  },
];

export function getSkillsForRole(role: string): string[] {
  return ROLE_SKILL_MAP[role] ?? [];
}

export function getCandidatesForRole(role: string): DummyCandidate[] {
  if (!role) return DUMMY_CANDIDATES;
  return DUMMY_CANDIDATES.filter((c) => c.role === role);
}

export function generateDummyAccessCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "GCC-";
  for (let i = 0; i < 5; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}
